In [1]:
import numpy as np
import pandas as pd
from optimal_designs import *

# Table 2

In [2]:
dict_df = {'Toxicity (Logistic)':[], 'Weights (Logistic)':[], 'Toxicity (Probit)':[], 'Weights (Probit)':[]}
gammas =  [0.1,0.2,0.3,0.4,0.5]
for g in gammas:
    H = load_param(model = 'logistic', g = g)['H']
    dis = A_optimal(model = 'logistic', g = g)
    dict_df['Toxicity (Logistic)'].append(tuple(H(dis.index).round(3)))
    dict_df['Weights (Logistic)'].append(tuple(dis.round(3)))
    #
    H = load_param(model = 'probit', g = g)['H']
    dis = A_optimal(model = 'probit', g = g)
    dict_df['Toxicity (Probit)'].append(tuple(H(dis.index).round(3)))
    dict_df['Weights (Probit)'].append(tuple(dis.round(3)))
pd.DataFrame(dict_df, index = gammas)

    Toxicity (Logistic) Weights (Logistic) Toxicity (Probit) Weights (Probit)
0.1      (0.118, 0.882)     (0.682, 0.318)      (0.09, 0.91)   (0.688, 0.312)
0.2      (0.146, 0.854)     (0.677, 0.323)    (0.111, 0.889)   (0.666, 0.334)
0.3      (0.169, 0.831)     (0.635, 0.365)    (0.126, 0.874)     (0.62, 0.38)
0.4      (0.184, 0.816)     (0.573, 0.427)    (0.136, 0.864)   (0.563, 0.437)
0.5      (0.189, 0.811)         (0.5, 0.5)      (0.14, 0.86)       (0.5, 0.5)

# Example restricted case

In [3]:
model, g ='logistic', 0.3
param = load_param(model = model, g = g)
H_inv, H = (param[el] for el in ['H_inv', 'H'])
#
# Compute de maximum dose by its toxicity
D = H_inv(0.4) 
print('The dose in Z_\Gamma for 0.4 toxicity:', round(D,6))
#
# Compute the design
dis = A_optimal(model = 'logistic', g = 0.3, D = D)
print(dis)
print('Toxicities:', H(dis.index).round(2))

The dose in Z_\Gamma for 0.4 toxicity: 0.092785
-0.438087    0.571271
 0.092785    0.428729
dtype: float64
Toxicities: Index([0.05, 0.4], dtype='float64')

# Table 3

In [4]:
dict_df = {'Toxicity (Logistic)':[], 'Weights (Logistic)':[], 'Toxicity (Probit)':[], 'Weights (Probit)':[]}
gammas =  [0.1,0.2,0.3,0.4,0.5]
for g in gammas:
    H = load_param(model = 'logistic', g = g)['H']
    dis = cc_optimal(model = 'logistic', g = g, tol = 0.85)
    dict_df['Toxicity (Logistic)'].append(tuple(H(dis.index).round(3)))
    dict_df['Weights (Logistic)'].append(tuple(dis.round(3)))
    #
    H = load_param(model = 'probit', g = g)['H']
    dis = cc_optimal(model = 'probit', g = g, tol = 0.85)
    dict_df['Toxicity (Probit)'].append(tuple(H(dis.index).round(3)))
    dict_df['Weights (Probit)'].append(tuple(dis.round(3)))
pd.DataFrame(dict_df, index = gammas)

    Toxicity (Logistic) Weights (Logistic) Toxicity (Probit) Weights (Probit)
0.1      (0.125, 0.875)     (0.805, 0.195)    (0.104, 0.896)   (0.847, 0.153)
0.2      (0.183, 0.817)     (0.851, 0.149)      (0.16, 0.84)   (0.834, 0.166)
0.3      (0.243, 0.757)     (0.804, 0.196)    (0.208, 0.792)   (0.765, 0.235)
0.4      (0.289, 0.711)     (0.688, 0.312)    (0.241, 0.759)     (0.65, 0.35)
0.5      (0.307, 0.693)         (0.5, 0.5)    (0.253, 0.747)       (0.5, 0.5)

# Example restricted case

In [6]:
model, g ='logistic', 0.3
param = load_param(model = model, g = g)
H_inv, H = (param[el] for el in ['H_inv', 'H'])
#
# Compute de maximum dose by its toxicity
D = H_inv(0.4) 
print('The dose in Z_\Gamma for 0.4 toxicity:', round(D,6))
#
# Compute the design
dis = cc_optimal(model = model, g = g, D = D, tol = 0.85)
print(dis)
print('Toxicities:', H(dis.index).round(2))

The dose in Z_\Gamma for 0.4 toxicity: 0.092785
-0.268619    0.413156
 0.092785    0.586844
dtype: float64
Toxicities: Index([0.11, 0.4], dtype='float64')

For the unrestricted case you don't always have a solution due to the required minimum efficiency.

In [7]:
model, g ='logistic', 0.3
H_inv = load_param(model = model, g = g)['H_inv']
H = load_param(model = model, g = g)['H']
D = H_inv(0.25)
print('The dose in Z_\Gamma for 0.2 toxicity:', round(D,6))
dis = cc_optimal(model = model, g = g, D = D, tol = 0.85)

The dose in Z_\Gamma for 0.2 toxicity: -0.052776
Error: Unable to find a design meeting the tolerance level 0.85 for mu, the maximum efficienci you can get with that restriction is 0.477